### ISSUE TITLE
Implement Structure in Docker

### ISSUE THREAD

**Issue by arthurhenrique** [berinhard/jazz-graph#1]
Implement the infrasctructure using docker swarm it would be a great, in order to start a neo4j from scratch and another dependencies...

**Comment by berinhard** [comment]
Hi @arthurhenrique! Thanks for your interest on this project. Unfortunately I'm noti being able to keep on growing it. It initial concept was an example to [a talk I gave at PythonBrasil[13]](https://www.youtube.com/watch?v=BWp_2xeVzoc) and since them it's idle.  

I'd love to help you with this docker dependencies though. Please, let me know if I can help you

**Comment by arthurhenrique** [comment]
Great talk @berinhard

Sorry, am I too late? 😅

**Comment by berinhard** [comment]
Hahaha, never! PR merged
